const { chromium } = require('/opt/npm-tools/node_modules/playwright');
const U = process.argv[2];
(async () => {
  const b = await chromium.launch(); const pg = await b.newPage({ viewport: { width: 1280, height: 720 } });
  const errs = []; pg.on('pageerror', e => errs.push(e.message));
  const shot = n => pg.screenshot({ path: 'shots/st-' + n + '.png' });
  const st = () => pg.evaluate(() => ({ tab, area, pos, n: list.length, cards: cards().length, detail, q: query, job: job.step || '', inst: Object.keys(installed) }));
  const k = async (key, n) => { for (let i = 0; i < (n || 1); i++) { await pg.keyboard.press(key); await pg.waitForTimeout(80); } await pg.waitForTimeout(200); };
  await pg.goto('file://' + U + '/store.html'); await pg.waitForTimeout(600);
  console.log('start', JSON.stringify(await st())); await shot(1);
  await k('ArrowUp'); console.log('up -> tabs', JSON.stringify(await st()));
  await k('ArrowRight'); console.log('games tab', JSON.stringify(await st())); await shot(2);
  await k('ArrowDown'); await k('ArrowDown', 30); console.log('deep', JSON.stringify(await st()));
  await pg.evaluate(() => { pos = cards().length - 1; paint(); }); await k('Enter'); console.log('show more', JSON.stringify(await st()));
  await k('/'); await pg.keyboard.type('dolph'); await pg.waitForTimeout(400); console.log('search', JSON.stringify(await st())); await shot(3);
  await k('Enter'); console.log('enter in search -> grid', JSON.stringify(await st()));
  await k('Enter'); console.log('detail', JSON.stringify(await st())); await shot(4);
  await k('Enter'); await pg.waitForTimeout(400); console.log('installing', JSON.stringify(await st())); await shot(5);
  await pg.waitForTimeout(2500); console.log('installed', JSON.stringify(await st()), await pg.evaluate(() => document.querySelector('#dbtns').textContent)); await shot(6);
  await k('ArrowRight'); await k('Enter'); console.log('confirm', await pg.evaluate(() => document.querySelector('#dbtns').textContent)); await shot(7);
  await k('ArrowRight'); await k('Enter'); await pg.waitForTimeout(1800); console.log('removed', JSON.stringify(await st()));
  await k('Escape'); console.log('back from detail', JSON.stringify(await st()));
  await k('Escape'); console.log('clear search', JSON.stringify(await st()));
  await pg.evaluate(() => { mockStoreEmpty = true; }).catch(() => {});
  await k('m'); await pg.waitForTimeout(4200);
  console.log('home tiles', await pg.evaluate(() => T1.map(t => t.id).join(',')));
  await pg.evaluate(() => { openG(4); }); await pg.waitForTimeout(400);
  console.log('settings rows', await pg.evaluate(() => items().map(r => r.t).join('|')));
  await pg.evaluate(() => updatesPanel()); await pg.waitForTimeout(300); console.log('updates', await pg.evaluate(() => P.rows.map(r => r.t).join('|'))); await shot(8);
  await k('Enter'); await pg.waitForTimeout(1600); console.log('after check', await pg.evaluate(() => document.querySelector('#ph').textContent + ' / ' + document.querySelector('#pp').textContent + ' / ' + (P ? P.rows.map(r => r.t).join('|') : ''))); await shot(9);
  await k('Enter'); await pg.waitForTimeout(1600); console.log('after apply', await pg.evaluate(() => document.querySelector('#pp').textContent + ' / ' + (P ? P.rows.map(r => r.t).join('|') : '')));
  await pg.evaluate(() => adminPanel()); await pg.waitForTimeout(300); await pg.keyboard.type('secret1'); await pg.focus('#apn2'); await pg.keyboard.type('secret1'); await shot(10); await k('Enter'); await pg.waitForTimeout(500);
  console.log('admin', await pg.evaluate(() => document.querySelector('#pp').textContent));
  await pg.evaluate(() => adminPanel()); await pg.waitForTimeout(300); console.log('admin again inputs', await pg.evaluate(() => document.querySelectorAll('#pbody input').length));
  await k('Escape'); await pg.evaluate(() => closeAll()); await pg.evaluate(() => terminal()); await pg.waitForTimeout(300); console.log('terminal running', await pg.evaluate(() => !!running.terminal));
  console.log('ERRORS', JSON.stringify(errs)); await b.close();
})();
